
// Autogenerated File. Do not edit
// Instead modify the files inside server/Scripts/EventBus/Messages

export interface AllMessage {
	topic: 'All';
	payload: {
		#TODO;
	};
}

export interface PingMessage {
	topic: 'Ping';
	payload: {
		#TODO;
	};
}

export interface PongMessage {
	topic: 'Pong';
	payload: {
		#TODO;
	};
}
