
// Autogenerated File. Do not edit
// Instead modify the files inside server/Scripts/EventBus/Messages

export interface AllMessage {
	topic: 'All';
	payload: {

	};
}

export interface GNC_StateMessage {
	topic: 'GNC_State';
	payload: {
		pos_x: number;
		pos_y: number;
		pos_z: number;
		ang_x: number;
		ang_y: number;
		ang_z: number
	};
}

export interface GNC_TargetsMessage {
	topic: 'GNC_Targets';
	payload: {
		linear_x: number;
		linear_y: number;
		linear_z: number;
		angular_x: number;
		angular_y: number;
		angular_z: number
	};
}

export interface PingMessage {
	topic: 'Ping';
	payload: {
		time_ping_sent: number
	};
}

export interface PongMessage {
	topic: 'Pong';
	payload: {
		time_ping_sent: number;
		time_server_send: number
	};
}

export interface SubscriptionsMessage {
	topic: 'Subscriptions';
	payload: {
		to_topics: Array
	};
}

export type Message = AllMessage | GNC_StateMessage | GNC_TargetsMessage | PingMessage | PongMessage | SubscriptionsMessage
